name: Build MobileFFmpeg (Android, arm64-v8a)

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    name: Android (ubuntu-latest, arm64-v8a only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for git describe

      # 1) Detect SDK/NDK on ubuntu-latest
      - name: Detect Android SDK/NDK
        shell: bash
        run: |
          set -euo pipefail
          SDK="/usr/local/lib/android/sdk"
          echo "ANDROID_SDK_ROOT=$SDK" >> "$GITHUB_ENV"
          echo "ANDROID_HOME=$SDK" >> "$GITHUB_ENV"
          LATEST_NDK="$(ls -1 "$SDK/ndk" | sort -V | tail -n1)"
          NDK="$SDK/ndk/$LATEST_NDK"
          echo "Using NDK: $NDK"
          echo "ANDROID_NDK_ROOT=$NDK" >> "$GITHUB_ENV"
          echo "ANDROID_NDK_HOME=$NDK" >> "$GITHUB_ENV"
          echo "$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin" >> "$GITHUB_PATH"

      - name: Show Android environment
        shell: bash
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
          ls -la "$ANDROID_SDK_ROOT/ndk" || true

      - name: Prepare git submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      # 6) Build (android.sh) – ARM64 only
      - name: Build (android.sh)
        shell: bash
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_ROOT: ${{ env.ANDROID_NDK_ROOT }}
          # ARCHITECTURES: ${{ env.ARCHITECTURES }}
          # FF_ARCHS: ${{ env.FF_ARCHS }}
          # CFLAGS: ${{ env.CFLAGS }}
          # LDFLAGS: ${{ env.LDFLAGS }}
        run: |
          export STRIP="$TOOLCHAIN/bin/llvm-strip"
          ./android.sh

      # 7) Always upload logs + prebuilt outputs (helps if anything fails)
      - name: Upload build logs and artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-and-logs
          path: |
            prebuilt/**
            **/*.log
            build/**/config.log
            ffbuild/**/config.log
          if-no-files-found: warn
